
version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: wordpress_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    image: wordpress:latest
    container_name: wordpress_app
    # ComposeはDBを起動してから、WPを起動する
    depends_on:
      - db
    ports:
      - "8080:80"
    restart: always
    # WPコンテナに渡す環境変数
    # WPがDBに接続する際に使う
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
    # ホスト側とコンテナ内のフォルダをマウントする
    volumes:
      - wp_data:/var/www/html

volumes:
  db_data:
  wp_data:


# Docker Composeは db（MariaDB） → wordpress の順で起動

# WordPressは環境変数を使って db に接続

# データは db_data, wp_data というボリュームに保存され、コンテナを削除しても残る

